FROM golang:1.24.1 AS build
WORKDIR /src

COPY go.mod go.sum* ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/broker ./cmd/broker

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
COPY --from=build /out/broker /broker
ENTRYPOINT ["/broker"]

