FROM alpine:3.21
RUN apk add --no-cache bash ca-certificates curl
WORKDIR /bootstrap
COPY docker/launcher/entrypoint.sh /bootstrap/entrypoint.sh
RUN chmod +x /bootstrap/entrypoint.sh
ENTRYPOINT ["/bootstrap/entrypoint.sh"]

