apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-ephemeral-runner-broker
  namespace: arc-systems
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unified-ephemeral-runner-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unified-ephemeral-runner-broker
    spec:
      serviceAccountName: unified-ephemeral-runner-broker
      containers:
        - name: broker
          image: ghcr.io/josh-archer/unified-ephemeral-runner-broker/broker:latest
          env:
            - name: UECB_CONFIG_PATH
              value: /etc/uecb/broker.yaml
            - name: UECB_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/uecb
            - name: uecb-github-app
              mountPath: /etc/uecb/github-app
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: unified-ephemeral-runner-broker-config
        - name: uecb-github-app
          secret:
            secretName: uecb-github-app
