apiVersion: v1
kind: Service
metadata:
  name: unified-ephemeral-runner-broker
  namespace: arc-systems
spec:
  selector:
    app.kubernetes.io/name: unified-ephemeral-runner-broker
  ports:
    - name: http
      port: 8080
      targetPort: http

